#!/bin/bash
"exec" "snakemake" "--printshellcmds" "--snakefile" "$0" "--jobs" "10"

import glob
import os.path
import itertools

SOURCE_DIR = '../../_m'
EXT = '.bam'


def sample_dict_iter(path, ext):
    for filename in glob.iglob(path+'/*'+ext):
        sample = os.path.basename(filename)[:-len(ext)]
        yield sample, {'filename': filename}
		

SAMPLE_DICT = {k:v for k,v in sample_dict_iter(SOURCE_DIR, EXT)}

rule all:
    input:
        expand('{sample}.counts.txt', sample=SAMPLE_DICT.keys())
        

rule featureCounts:
	input:
		bam = lambda x: SAMPLE_DICT[x.sample]['filename'],
		gtf = '/ceph/genome/human/gencode37/GRCh38.p13.PRI/gtf.PRI/_m/gencode.v37.primary_assembly.annotation.gtf'
	output:
		'{sample}.counts.txt'
	log:
		stderr = '{sample}.stderr',
		stdout = '{sample}.stdout'
	shell:
		'/ceph/opt/subread-2.0.1_modified_for_repeats/subread-2.0.1-source/bin/featureCounts '
		'-T 1 -M --primary -p -C -s 2 '
		'-a {input.gtf} '
		'-o {output} {input.bam} '
		'2>{log.stderr} > {log.stdout}'
